services:
  - type: web
    name: invisible-cloak-app
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      echo "Installing dependencies..."
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      echo "Build complete!"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        sync: false
