services:
  - type: web
    name: invisible-cloak-app
    runtime: python3
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PIP_NO_CACHE_DIR
        value: 1
